macro(find_smart_gcc REQUIRED_STD)
    if(NOT CMAKE_CXX_COMPILER)
        if(${REQUIRED_STD} EQUAL 26)
            set(CANDIDATES g++-16 g++-15 g++-14 g++)
        elseif(${REQUIRED_STD} EQUAL 20)
            set(CANDIDATES g++-16 g++-15 g++-14 g++-13 g++-12 g++-11 g++-10 g++)
        elseif(${REQUIRED_STD} EQUAL 17)
            set(CANDIDATES g++-16 g++-15 g++-14 g++-13 g++-12 g++-11 g++-10 g++-9 g++-8 g++)
        else()
            set(CANDIDATES g++-16 g++-15 g++-14 g++-13 g++-12 g++-11 g++-10 g++-9 g++-8 g++-7 g++)
        endif()
        
        set(FOUND_SMART_COMPILER "")
        foreach(COMPILER ${CANDIDATES})
            find_program(COMPILER_PATH ${COMPILER})
            if(COMPILER_PATH)
                execute_process(COMMAND ${COMPILER_PATH} -std=c++${REQUIRED_STD} -E - 
                                RESULT_VARIABLE GCC_STD_SUPPORT
                                ERROR_QUIET OUTPUT_QUIET INPUT_FILE /dev/null)
                if(GCC_STD_SUPPORT EQUAL 0)
                    set(FOUND_SMART_COMPILER ${COMPILER_PATH})
                    break()
                endif()
            endif()
        endforeach()
        
        if(FOUND_SMART_COMPILER)
            set(CMAKE_CXX_COMPILER ${FOUND_SMART_COMPILER})
            message(STATUS "SmartGCC: Selected ${FOUND_SMART_COMPILER} for C++${REQUIRED_STD}")
        else()
            message(WARNING "SmartGCC: Could not find a suitable GCC compiler supporting C++${REQUIRED_STD}. CMake will use its default.")
        endif()
    endif()
endmacro()
