
#pragma once

#include "near_perfect_hash.hpp"

enum class FixTags
{
    Account = 1,
    AdvId = 2,
    AdvRefID = 3,
    AdvSide = 4,
    AdvTransType = 5,
    AvgPx = 6,
    BeginSeqNo = 7,
    BeginString = 8,
    BodyLength = 9,
    CheckSum = 10,
    ClOrdID = 11,
    Commission = 12,
    CommType = 13,
    CumQty = 14,
    Currency = 15,
    EndSeqNo = 16,
    ExecID = 17,
    ExecInst = 18,
    ExecRefID = 19,
    ExecTransType = 20,
    HandlInst = 21,
    IDSource = 22,
    IOIid = 23,
    IOIOthSvc = 24,
    IOIQltyInd = 25,
    IOIRefID = 26,
    IOIShares = 27,
    IOITransType = 28,
    LastCapacity = 29,
    LastMkt = 30,
    LastPx = 31,
    LastShares = 32,
    LinesOfText = 33,
    MsgSeqNum = 34,
    MsgType = 35,
    NewSeqNo = 36,
    OrderID = 37,
    OrderQty = 38,
    OrdStatus = 39,
    OrdType = 40,
    OrigClOrdID = 41,
    OrigTime = 42,
    PossDupFlag = 43,
    Price = 44,
    RefSeqNum = 45,
    RelatdSym = 46,
    Rule80A = 47,
    SecurityID = 48,
    SenderCompID = 49,
    SenderSubID = 50,
    SendingDate = 51,
    SendingTime = 52,
    Shares = 53,
    Side = 54,
    Symbol = 55,
    TargetCompID = 56,
    TargetSubID = 57,
    Text = 58,
    TimeInForce = 59,
    TransactTime = 60,
    Urgency = 61,
    ValidUntilTime = 62,
    SettlmntTyp = 63,
    FutSettDate = 64,
    SymbolSfx = 65,
    ListID = 66,
    ListSeqNo = 67,
    TotNoOrders = 68,
    ListExecInst = 69,
    AllocID = 70,
    AllocTransType = 71,
    RefAllocID = 72,
    NoOrders = 73,
    AvgPrxPrecision = 74,
    TradeDate = 75,
    ExecBroker = 76,
    OpenClose = 77,
    NoAllocs = 78,
    AllocAccount = 79,
    AllocShares = 80,
    ProcessCode = 81,
    NoRpts = 82,
    RptSeq = 83,
    CxlQty = 84,
    NoDlvyInst = 85,
    DlvyInst = 86,
    AllocStatus = 87,
    AllocRejCode = 88,
    Signature = 89,
    SecureDataLen = 90,
    SecureData = 91,
    BrokerOfCredit = 92,
    SignatureLength = 93,
    EmailType = 94,
    RawDataLength = 95,
    RawData = 96,
    PossResend = 97,
    EncryptMethod = 98,
    StopPx = 99,
    ExDestination = 100,
    CxlRejReason = 102,
    OrdRejReason = 103,
    IOIQualifier = 104,
    WaveNo = 105,
    Issuer = 106,
    SecurityDesc = 107,
    HeartBtInt = 108,
    ClientID = 109,
    MinQty = 110,
    MaxFloor = 111,
    TestReqID = 112,
    ReportToExch = 113,
    LocateReqd = 114,
    OnBehalfOfCompID = 115,
    OnBehalfOfSubID = 116,
    QuoteID = 117,
    NetMoney = 118,
    SettlCurrAmt = 119,
    SettlCurrency = 120,
    ForexReq = 121,
    OrigSendingTime = 122,
    GapFillFlag = 123,
    NoExecs = 124,
    CxlType = 125,
    ExpireTime = 126,
    DKReason = 127,
    DeliverToCompID = 128,
    DeliverToSubID = 129,
    IOINaturalFlag = 130,
    QuoteReqID = 131,
    BidPx = 132,
    OfferPx = 133,
    BidSize = 134,
    OfferSize = 135,
    NoMiscFees = 136,
    MiscFeeAmt = 137,
    MiscFeeCurr = 138,
    MiscFeeType = 139,
    PrevClosePx = 140,
    ResetSeqNumFlag = 141,
    SenderLocationID = 142,
    TargetLocationID = 143,
    OnBehalfOfLocationID = 144,
    DeliverToLocationID = 145,
    NoRelatedSym = 146,
    Subject = 147,
    Headline = 148,
    URLLink = 149,
    ExecType = 150,
    LeavesQty = 151,
    CashOrderQty = 152,
    AllocAvgPx = 153,
    AllocNetMoney = 154,
    SettlCurrFxRate = 155,
    SettlCurrFxRateCalc = 156,
    NumDaysInterest = 157,
    AccruedInterestRate = 158,
    AccruedInterestAmt = 159,
    SettlInstMode = 160,
    AllocText = 161,
    SettlInstID = 162,
    SettlInstTransType = 163,
    EmailThreadID = 164,
    SettlInstSource = 165,
    SettlLocation = 166,
    SecurityType = 167,
    EffectiveTime = 168,
    StandInstDbType = 169,
    StandInstDbName = 170,
    StandInstDbID = 171,
    SettlDeliveryType = 172,
    SettlDepositoryCode = 173,
    SettlBrkrCode = 174,
    SettlInstCode = 175,
    SecuritySettlAgentName = 176,
    SecuritySettlAgentCode = 177,
    SecuritySettlAgentAcctNum = 178,
    SecuritySettlAgentAcctName = 179,
    SecuritySettlAgentContactName = 180,
    SecuritySettlAgentContactPhone = 181,
    CashSettlAgentName = 182,
    CashSettlAgentCode = 183,
    CashSettlAgentAcctNum = 184,
    CashSettlAgentAcctName = 185,
    CashSettlAgentContactName = 186,
    CashSettlAgentContactPhone = 187,
    BidSpotRate = 188,
    BidForwardPoints = 189,
    OfferSpotRate = 190,
    OfferForwardPoints = 191,
    OrderQty2 = 192,
    FutSettDate2 = 193,
    LastSpotRate = 194,
    LastForwardPoints = 195,
    AllocLinkID = 196,
    AllocLinkType = 197,
    SecondaryOrderID = 198,
    NoIOIQualifiers = 199,
    MaturityMonthYear = 200,
    PutOrCall = 201,
    StrikePrice = 202,
    CoveredOrUncovered = 203,
    CustomerOrFirm = 204,
    MaturityDay = 205,
    OptAttribute = 206,
    SecurityExchange = 207,
    NotifyBrokerOfCredit = 208,
    AllocHandlInst = 209,
    MaxShow = 210,
    PegDifference = 211,
    XmlDataLen = 212,
    XmlData = 213,
    SettlInstRefID = 214,
    NoRoutingIDs = 215,
    RoutingType = 216,
    RoutingID = 217,
    SpreadToBenchmark = 218,
    Benchmark = 219,
    CouponRate = 223,
    ContractMultiplier = 231,
    MDReqID = 262,
    SubscriptionRequestType = 263,
    MarketDepth = 264,
    MDUpdateType = 265,
    AggregatedBook = 266,
    NoMDEntryTypes = 267,
    NoMDEntries = 268,
    MDEntryType = 269,
    MDEntryPx = 270,
    MDEntrySize = 271,
    MDEntryDate = 272,
    MDEntryTime = 273,
    TickDirection = 274,
    MDMkt = 275,
    QuoteCondition = 276,
    TradeCondition = 277,
    MDEntryID = 278,
    MDUpdateAction = 279,
    MDEntryRefID = 280,
    MDReqRejReason = 281,
    MDEntryOriginator = 282,
    LocationID = 283,
    DeskID = 284,
    DeleteReason = 285,
    OpenCloseSettleFlag = 286,
    SellerDays = 287,
    MDEntryBuyer = 288,
    MDEntrySeller = 289,
    MDEntryPositionNo = 290,
    FinancialStatus = 291,
    CorporateAction = 292,
    DefBidSize = 293,
    DefOfferSize = 294,
    NoQuoteEntries = 295,
    NoQuoteSets = 296,
    QuoteAckStatus = 297,
    QuoteCancelType = 298,
    QuoteEntryID = 299,
    QuoteRejectReason = 300,
    QuoteResponseLevel = 301,
    QuoteSetID = 302,
    QuoteRequestType = 303,
    TotQuoteEntries = 304,
    UnderlyingIDSource = 305,
    UnderlyingIssuer = 306,
    UnderlyingSecurityDesc = 307,
    UnderlyingSecurityExchange = 308,
    UnderlyingSecurityID = 309,
    UnderlyingSecurityType = 310,
    UnderlyingSymbol = 311,
    UnderlyingSymbolSfx = 312,
    UnderlyingMaturityMonthYear = 313,
    UnderlyingMaturityDay = 314,
    UnderlyingPutOrCall = 315,
    UnderlyingStrikePrice = 316,
    UnderlyingOptAttribute = 317,
    UnderlyingCurrency = 318,
    RatioQty = 319,
    SecurityReqID = 320,
    SecurityRequestType = 321,
    SecurityResponseID = 322,
    SecurityResponseType = 323,
    SecurityStatusReqID = 324,
    UnsolicitedIndicator = 325,
    SecurityTradingStatus = 326,
    HaltReasonChar = 327,
    InViewOfCommon = 328,
    DueToRelated = 329,
    BuyVolume = 330,
    SellVolume = 331,
    HighPx = 332,
    LowPx = 333,
    Adjustment = 334,
    TradSesReqID = 335,
    TradingSessionID = 336,
    ContraTrader = 337,
    TradSesMethod = 338,
    TradSesMode = 339,
    TradSesStatus = 340,
    TradSesStartTime = 341,
    TradSesOpenTime = 342,
    TradSesPreCloseTime = 343,
    TradSesCloseTime = 344,
    TradSesEndTime = 345,
    NumberOfOrders = 346,
    MessageEncoding = 347,
    EncodedIssuerLen = 348,
    EncodedIssuer = 349,
    EncodedSecurityDescLen = 350,
    EncodedSecurityDesc = 351,
    EncodedListExecInstLen = 352,
    EncodedListExecInst = 353,
    EncodedTextLen = 354,
    EncodedText = 355,
    EncodedSubjectLen = 356,
    EncodedSubject = 357,
    EncodedHeadlineLen = 358,
    EncodedHeadline = 359,
    EncodedAllocTextLen = 360,
    EncodedAllocText = 361,
    EncodedUnderlyingIssuerLen = 362,
    EncodedUnderlyingIssuer = 363,
    EncodedUnderlyingSecurityDescLen = 364,
    EncodedUnderlyingSecurityDesc = 365,
    AllocPrice = 366,
    QuoteSetValidUntilTime = 367,
    QuoteEntryRejectReason = 368,
    LastMsgSeqNumProcessed = 369,
    OnBehalfOfSendingTime = 370,
    RefTagID = 371,
    RefMsgType = 372,
    SessionRejectReason = 373,
    BidRequestTransType = 374,
    ContraBroker = 375,
    ComplianceID = 376,
    SolicitedFlag = 377,
    ExecRestatementReason = 378,
    BusinessRejectRefID = 379,
    BusinessRejectReason = 380,
    GrossTradeAmt = 381,
    NoContraBrokers = 382,
    MaxMessageSize = 383,
    NoMsgTypes = 384,
    MsgDirection = 385,
    NoTradingSessions = 386,
    TotalVolumeTraded = 387,
    DiscretionInst = 388,
    DiscretionOffset = 389,
    BidID = 390,
    ClientBidID = 391,
    ListName = 392,
    TotalNumSecurities = 393,
    BidType = 394,
    NumTickets = 395,
    SideValue1 = 396,
    SideValue2 = 397,
    NoBidDescriptors = 398,
    BidDescriptorType = 399,
    BidDescriptor = 400,
    SideValueInd = 401,
    LiquidityPctLow = 402,
    LiquidityPctHigh = 403,
    LiquidityValue = 404,
    EFPTrackingError = 405,
    FairValue = 406,
    OutsideIndexPct = 407,
    ValueOfFutures = 408,
    LiquidityIndType = 409,
    WtAverageLiquidity = 410,
    ExchangeForPhysical = 411,
    OutMainCntryUIndex = 412,
    CrossPercent = 413,
    ProgRptReqs = 414,
    ProgPeriodInterval = 415,
    IncTaxInd = 416,
    NumBidders = 417,
    TradeType = 418,
    BasisPxType = 419,
    NoBidComponents = 420,
    Country = 421,
    TotNoStrikes = 422,
    PriceType = 423,
    DayOrderQty = 424,
    DayCumQty = 425,
    DayAvgPx = 426,
    GTBookingInst = 427,
    NoStrikes = 428,
    ListStatusType = 429,
    NetGrossInd = 430,
    ListOrderStatus = 431,
    ExpireDate = 432,
    ListExecInstType = 433,
    CxlRejResponseTo = 434,
    UnderlyingCouponRate = 435,
    UnderlyingContractMultiplier = 436,
    ContraTradeQty = 437,
    ContraTradeTime = 438,
    ClearingFirm = 439,
    ClearingAccount = 440,
    LiquidityNumSecurities = 441,
    MultiLegReportingType = 442,
    StrikeTime = 443,
    ListStatusText = 444,
    EncodedListStatusTextLen = 445,
    EncodedListStatusText = 446,
};


CONSTEXPR_OR_CONST_FOR_HASH  NearPerfectHash<FixTags, 405> FixTagHash(    make_enum_name(FixTags::Account,"Account"),
        make_enum_name(FixTags::AdvId,"AdvId"),
        make_enum_name(FixTags::AdvRefID,"AdvRefID"),
        make_enum_name(FixTags::AdvSide,"AdvSide"),
        make_enum_name(FixTags::AdvTransType,"AdvTransType"),
        make_enum_name(FixTags::AvgPx,"AvgPx"),
        make_enum_name(FixTags::BeginSeqNo,"BeginSeqNo"),
        make_enum_name(FixTags::BeginString,"BeginString"),
        make_enum_name(FixTags::BodyLength,"BodyLength"),
        make_enum_name(FixTags::CheckSum,"CheckSum"),
        make_enum_name(FixTags::ClOrdID,"ClOrdID"),
        make_enum_name(FixTags::Commission,"Commission"),
        make_enum_name(FixTags::CommType,"CommType"),
        make_enum_name(FixTags::CumQty,"CumQty"),
        make_enum_name(FixTags::Currency,"Currency"),
        make_enum_name(FixTags::EndSeqNo,"EndSeqNo"),
        make_enum_name(FixTags::ExecID,"ExecID"),
        make_enum_name(FixTags::ExecInst,"ExecInst"),
        make_enum_name(FixTags::ExecRefID,"ExecRefID"),
        make_enum_name(FixTags::ExecTransType,"ExecTransType"),
        make_enum_name(FixTags::HandlInst,"HandlInst"),
        make_enum_name(FixTags::IDSource,"IDSource"),
        make_enum_name(FixTags::IOIid,"IOIid"),
        make_enum_name(FixTags::IOIOthSvc,"IOIOthSvc"),
        make_enum_name(FixTags::IOIQltyInd,"IOIQltyInd"),
        make_enum_name(FixTags::IOIRefID,"IOIRefID"),
        make_enum_name(FixTags::IOIShares,"IOIShares"),
        make_enum_name(FixTags::IOITransType,"IOITransType"),
        make_enum_name(FixTags::LastCapacity,"LastCapacity"),
        make_enum_name(FixTags::LastMkt,"LastMkt"),
        make_enum_name(FixTags::LastPx,"LastPx"),
        make_enum_name(FixTags::LastShares,"LastShares"),
        make_enum_name(FixTags::LinesOfText,"LinesOfText"),
        make_enum_name(FixTags::MsgSeqNum,"MsgSeqNum"),
        make_enum_name(FixTags::MsgType,"MsgType"),
        make_enum_name(FixTags::NewSeqNo,"NewSeqNo"),
        make_enum_name(FixTags::OrderID,"OrderID"),
        make_enum_name(FixTags::OrderQty,"OrderQty"),
        make_enum_name(FixTags::OrdStatus,"OrdStatus"),
        make_enum_name(FixTags::OrdType,"OrdType"),
        make_enum_name(FixTags::OrigClOrdID,"OrigClOrdID"),
        make_enum_name(FixTags::OrigTime,"OrigTime"),
        make_enum_name(FixTags::PossDupFlag,"PossDupFlag"),
        make_enum_name(FixTags::Price,"Price"),
        make_enum_name(FixTags::RefSeqNum,"RefSeqNum"),
        make_enum_name(FixTags::RelatdSym,"RelatdSym"),
        make_enum_name(FixTags::Rule80A,"Rule80A"),
        make_enum_name(FixTags::SecurityID,"SecurityID"),
        make_enum_name(FixTags::SenderCompID,"SenderCompID"),
        make_enum_name(FixTags::SenderSubID,"SenderSubID"),
        make_enum_name(FixTags::SendingDate,"SendingDate"),
        make_enum_name(FixTags::SendingTime,"SendingTime"),
        make_enum_name(FixTags::Shares,"Shares"),
        make_enum_name(FixTags::Side,"Side"),
        make_enum_name(FixTags::Symbol,"Symbol"),
        make_enum_name(FixTags::TargetCompID,"TargetCompID"),
        make_enum_name(FixTags::TargetSubID,"TargetSubID"),
        make_enum_name(FixTags::Text,"Text"),
        make_enum_name(FixTags::TimeInForce,"TimeInForce"),
        make_enum_name(FixTags::TransactTime,"TransactTime"),
        make_enum_name(FixTags::Urgency,"Urgency"),
        make_enum_name(FixTags::ValidUntilTime,"ValidUntilTime"),
        make_enum_name(FixTags::SettlmntTyp,"SettlmntTyp"),
        make_enum_name(FixTags::FutSettDate,"FutSettDate"),
        make_enum_name(FixTags::SymbolSfx,"SymbolSfx"),
        make_enum_name(FixTags::ListID,"ListID"),
        make_enum_name(FixTags::ListSeqNo,"ListSeqNo"),
        make_enum_name(FixTags::TotNoOrders,"TotNoOrders"),
        make_enum_name(FixTags::ListExecInst,"ListExecInst"),
        make_enum_name(FixTags::AllocID,"AllocID"),
        make_enum_name(FixTags::AllocTransType,"AllocTransType"),
        make_enum_name(FixTags::RefAllocID,"RefAllocID"),
        make_enum_name(FixTags::NoOrders,"NoOrders"),
        make_enum_name(FixTags::AvgPrxPrecision,"AvgPrxPrecision"),
        make_enum_name(FixTags::TradeDate,"TradeDate"),
        make_enum_name(FixTags::ExecBroker,"ExecBroker"),
        make_enum_name(FixTags::OpenClose,"OpenClose"),
        make_enum_name(FixTags::NoAllocs,"NoAllocs"),
        make_enum_name(FixTags::AllocAccount,"AllocAccount"),
        make_enum_name(FixTags::AllocShares,"AllocShares"),
        make_enum_name(FixTags::ProcessCode,"ProcessCode"),
        make_enum_name(FixTags::NoRpts,"NoRpts"),
        make_enum_name(FixTags::RptSeq,"RptSeq"),
        make_enum_name(FixTags::CxlQty,"CxlQty"),
        make_enum_name(FixTags::NoDlvyInst,"NoDlvyInst"),
        make_enum_name(FixTags::DlvyInst,"DlvyInst"),
        make_enum_name(FixTags::AllocStatus,"AllocStatus"),
        make_enum_name(FixTags::AllocRejCode,"AllocRejCode"),
        make_enum_name(FixTags::Signature,"Signature"),
        make_enum_name(FixTags::SecureDataLen,"SecureDataLen"),
        make_enum_name(FixTags::SecureData,"SecureData"),
        make_enum_name(FixTags::BrokerOfCredit,"BrokerOfCredit"),
        make_enum_name(FixTags::SignatureLength,"SignatureLength"),
        make_enum_name(FixTags::EmailType,"EmailType"),
        make_enum_name(FixTags::RawDataLength,"RawDataLength"),
        make_enum_name(FixTags::RawData,"RawData"),
        make_enum_name(FixTags::PossResend,"PossResend"),
        make_enum_name(FixTags::EncryptMethod,"EncryptMethod"),
        make_enum_name(FixTags::StopPx,"StopPx"),
        make_enum_name(FixTags::ExDestination,"ExDestination"),
        make_enum_name(FixTags::CxlRejReason,"CxlRejReason"),
        make_enum_name(FixTags::OrdRejReason,"OrdRejReason"),
        make_enum_name(FixTags::IOIQualifier,"IOIQualifier"),
        make_enum_name(FixTags::WaveNo,"WaveNo"),
        make_enum_name(FixTags::Issuer,"Issuer"),
        make_enum_name(FixTags::SecurityDesc,"SecurityDesc"),
        make_enum_name(FixTags::HeartBtInt,"HeartBtInt"),
        make_enum_name(FixTags::ClientID,"ClientID"),
        make_enum_name(FixTags::MinQty,"MinQty"),
        make_enum_name(FixTags::MaxFloor,"MaxFloor"),
        make_enum_name(FixTags::TestReqID,"TestReqID"),
        make_enum_name(FixTags::ReportToExch,"ReportToExch"),
        make_enum_name(FixTags::LocateReqd,"LocateReqd"),
        make_enum_name(FixTags::OnBehalfOfCompID,"OnBehalfOfCompID"),
        make_enum_name(FixTags::OnBehalfOfSubID,"OnBehalfOfSubID"),
        make_enum_name(FixTags::QuoteID,"QuoteID"),
        make_enum_name(FixTags::NetMoney,"NetMoney"),
        make_enum_name(FixTags::SettlCurrAmt,"SettlCurrAmt"),
        make_enum_name(FixTags::SettlCurrency,"SettlCurrency"),
        make_enum_name(FixTags::ForexReq,"ForexReq"),
        make_enum_name(FixTags::OrigSendingTime,"OrigSendingTime"),
        make_enum_name(FixTags::GapFillFlag,"GapFillFlag"),
        make_enum_name(FixTags::NoExecs,"NoExecs"),
        make_enum_name(FixTags::CxlType,"CxlType"),
        make_enum_name(FixTags::ExpireTime,"ExpireTime"),
        make_enum_name(FixTags::DKReason,"DKReason"),
        make_enum_name(FixTags::DeliverToCompID,"DeliverToCompID"),
        make_enum_name(FixTags::DeliverToSubID,"DeliverToSubID"),
        make_enum_name(FixTags::IOINaturalFlag,"IOINaturalFlag"),
        make_enum_name(FixTags::QuoteReqID,"QuoteReqID"),
        make_enum_name(FixTags::BidPx,"BidPx"),
        make_enum_name(FixTags::OfferPx,"OfferPx"),
        make_enum_name(FixTags::BidSize,"BidSize"),
        make_enum_name(FixTags::OfferSize,"OfferSize"),
        make_enum_name(FixTags::NoMiscFees,"NoMiscFees"),
        make_enum_name(FixTags::MiscFeeAmt,"MiscFeeAmt"),
        make_enum_name(FixTags::MiscFeeCurr,"MiscFeeCurr"),
        make_enum_name(FixTags::MiscFeeType,"MiscFeeType"),
        make_enum_name(FixTags::PrevClosePx,"PrevClosePx"),
        make_enum_name(FixTags::ResetSeqNumFlag,"ResetSeqNumFlag"),
        make_enum_name(FixTags::SenderLocationID,"SenderLocationID"),
        make_enum_name(FixTags::TargetLocationID,"TargetLocationID"),
        make_enum_name(FixTags::OnBehalfOfLocationID,"OnBehalfOfLocationID"),
        make_enum_name(FixTags::DeliverToLocationID,"DeliverToLocationID"),
        make_enum_name(FixTags::NoRelatedSym,"NoRelatedSym"),
        make_enum_name(FixTags::Subject,"Subject"),
        make_enum_name(FixTags::Headline,"Headline"),
        make_enum_name(FixTags::URLLink,"URLLink"),
        make_enum_name(FixTags::ExecType,"ExecType"),
        make_enum_name(FixTags::LeavesQty,"LeavesQty"),
        make_enum_name(FixTags::CashOrderQty,"CashOrderQty"),
        make_enum_name(FixTags::AllocAvgPx,"AllocAvgPx"),
        make_enum_name(FixTags::AllocNetMoney,"AllocNetMoney"),
        make_enum_name(FixTags::SettlCurrFxRate,"SettlCurrFxRate"),
        make_enum_name(FixTags::SettlCurrFxRateCalc,"SettlCurrFxRateCalc"),
        make_enum_name(FixTags::NumDaysInterest,"NumDaysInterest"),
        make_enum_name(FixTags::AccruedInterestRate,"AccruedInterestRate"),
        make_enum_name(FixTags::AccruedInterestAmt,"AccruedInterestAmt"),
        make_enum_name(FixTags::SettlInstMode,"SettlInstMode"),
        make_enum_name(FixTags::AllocText,"AllocText"),
        make_enum_name(FixTags::SettlInstID,"SettlInstID"),
        make_enum_name(FixTags::SettlInstTransType,"SettlInstTransType"),
        make_enum_name(FixTags::EmailThreadID,"EmailThreadID"),
        make_enum_name(FixTags::SettlInstSource,"SettlInstSource"),
        make_enum_name(FixTags::SettlLocation,"SettlLocation"),
        make_enum_name(FixTags::SecurityType,"SecurityType"),
        make_enum_name(FixTags::EffectiveTime,"EffectiveTime"),
        make_enum_name(FixTags::StandInstDbType,"StandInstDbType"),
        make_enum_name(FixTags::StandInstDbName,"StandInstDbName"),
        make_enum_name(FixTags::StandInstDbID,"StandInstDbID"),
        make_enum_name(FixTags::SettlDeliveryType,"SettlDeliveryType"),
        make_enum_name(FixTags::SettlDepositoryCode,"SettlDepositoryCode"),
        make_enum_name(FixTags::SettlBrkrCode,"SettlBrkrCode"),
        make_enum_name(FixTags::SettlInstCode,"SettlInstCode"),
        make_enum_name(FixTags::SecuritySettlAgentName,"SecuritySettlAgentName"),
        make_enum_name(FixTags::SecuritySettlAgentCode,"SecuritySettlAgentCode"),
        make_enum_name(FixTags::SecuritySettlAgentAcctNum,"SecuritySettlAgentAcctNum"),
        make_enum_name(FixTags::SecuritySettlAgentAcctName,"SecuritySettlAgentAcctName"),
        make_enum_name(FixTags::SecuritySettlAgentContactName,"SecuritySettlAgentContactName"),
        make_enum_name(FixTags::SecuritySettlAgentContactPhone,"SecuritySettlAgentContactPhone"),
        make_enum_name(FixTags::CashSettlAgentName,"CashSettlAgentName"),
        make_enum_name(FixTags::CashSettlAgentCode,"CashSettlAgentCode"),
        make_enum_name(FixTags::CashSettlAgentAcctNum,"CashSettlAgentAcctNum"),
        make_enum_name(FixTags::CashSettlAgentAcctName,"CashSettlAgentAcctName"),
        make_enum_name(FixTags::CashSettlAgentContactName,"CashSettlAgentContactName"),
        make_enum_name(FixTags::CashSettlAgentContactPhone,"CashSettlAgentContactPhone"),
        make_enum_name(FixTags::BidSpotRate,"BidSpotRate"),
        make_enum_name(FixTags::BidForwardPoints,"BidForwardPoints"),
        make_enum_name(FixTags::OfferSpotRate,"OfferSpotRate"),
        make_enum_name(FixTags::OfferForwardPoints,"OfferForwardPoints"),
        make_enum_name(FixTags::OrderQty2,"OrderQty2"),
        make_enum_name(FixTags::FutSettDate2,"FutSettDate2"),
        make_enum_name(FixTags::LastSpotRate,"LastSpotRate"),
        make_enum_name(FixTags::LastForwardPoints,"LastForwardPoints"),
        make_enum_name(FixTags::AllocLinkID,"AllocLinkID"),
        make_enum_name(FixTags::AllocLinkType,"AllocLinkType"),
        make_enum_name(FixTags::SecondaryOrderID,"SecondaryOrderID"),
        make_enum_name(FixTags::NoIOIQualifiers,"NoIOIQualifiers"),
        make_enum_name(FixTags::MaturityMonthYear,"MaturityMonthYear"),
        make_enum_name(FixTags::PutOrCall,"PutOrCall"),
        make_enum_name(FixTags::StrikePrice,"StrikePrice"),
        make_enum_name(FixTags::CoveredOrUncovered,"CoveredOrUncovered"),
        make_enum_name(FixTags::CustomerOrFirm,"CustomerOrFirm"),
        make_enum_name(FixTags::MaturityDay,"MaturityDay"),
        make_enum_name(FixTags::OptAttribute,"OptAttribute"),
        make_enum_name(FixTags::SecurityExchange,"SecurityExchange"),
        make_enum_name(FixTags::NotifyBrokerOfCredit,"NotifyBrokerOfCredit"),
        make_enum_name(FixTags::AllocHandlInst,"AllocHandlInst"),
        make_enum_name(FixTags::MaxShow,"MaxShow"),
        make_enum_name(FixTags::PegDifference,"PegDifference"),
        make_enum_name(FixTags::XmlDataLen,"XmlDataLen"),
        make_enum_name(FixTags::XmlData,"XmlData"),
        make_enum_name(FixTags::SettlInstRefID,"SettlInstRefID"),
        make_enum_name(FixTags::NoRoutingIDs,"NoRoutingIDs"),
        make_enum_name(FixTags::RoutingType,"RoutingType"),
        make_enum_name(FixTags::RoutingID,"RoutingID"),
        make_enum_name(FixTags::SpreadToBenchmark,"SpreadToBenchmark"),
        make_enum_name(FixTags::Benchmark,"Benchmark"),
        make_enum_name(FixTags::CouponRate,"CouponRate"),
        make_enum_name(FixTags::ContractMultiplier,"ContractMultiplier"),
        make_enum_name(FixTags::MDReqID,"MDReqID"),
        make_enum_name(FixTags::SubscriptionRequestType,"SubscriptionRequestType"),
        make_enum_name(FixTags::MarketDepth,"MarketDepth"),
        make_enum_name(FixTags::MDUpdateType,"MDUpdateType"),
        make_enum_name(FixTags::AggregatedBook,"AggregatedBook"),
        make_enum_name(FixTags::NoMDEntryTypes,"NoMDEntryTypes"),
        make_enum_name(FixTags::NoMDEntries,"NoMDEntries"),
        make_enum_name(FixTags::MDEntryType,"MDEntryType"),
        make_enum_name(FixTags::MDEntryPx,"MDEntryPx"),
        make_enum_name(FixTags::MDEntrySize,"MDEntrySize"),
        make_enum_name(FixTags::MDEntryDate,"MDEntryDate"),
        make_enum_name(FixTags::MDEntryTime,"MDEntryTime"),
        make_enum_name(FixTags::TickDirection,"TickDirection"),
        make_enum_name(FixTags::MDMkt,"MDMkt"),
        make_enum_name(FixTags::QuoteCondition,"QuoteCondition"),
        make_enum_name(FixTags::TradeCondition,"TradeCondition"),
        make_enum_name(FixTags::MDEntryID,"MDEntryID"),
        make_enum_name(FixTags::MDUpdateAction,"MDUpdateAction"),
        make_enum_name(FixTags::MDEntryRefID,"MDEntryRefID"),
        make_enum_name(FixTags::MDReqRejReason,"MDReqRejReason"),
        make_enum_name(FixTags::MDEntryOriginator,"MDEntryOriginator"),
        make_enum_name(FixTags::LocationID,"LocationID"),
        make_enum_name(FixTags::DeskID,"DeskID"),
        make_enum_name(FixTags::DeleteReason,"DeleteReason"),
        make_enum_name(FixTags::OpenCloseSettleFlag,"OpenCloseSettleFlag"),
        make_enum_name(FixTags::SellerDays,"SellerDays"),
        make_enum_name(FixTags::MDEntryBuyer,"MDEntryBuyer"),
        make_enum_name(FixTags::MDEntrySeller,"MDEntrySeller"),
        make_enum_name(FixTags::MDEntryPositionNo,"MDEntryPositionNo"),
        make_enum_name(FixTags::FinancialStatus,"FinancialStatus"),
        make_enum_name(FixTags::CorporateAction,"CorporateAction"),
        make_enum_name(FixTags::DefBidSize,"DefBidSize"),
        make_enum_name(FixTags::DefOfferSize,"DefOfferSize"),
        make_enum_name(FixTags::NoQuoteEntries,"NoQuoteEntries"),
        make_enum_name(FixTags::NoQuoteSets,"NoQuoteSets"),
        make_enum_name(FixTags::QuoteAckStatus,"QuoteAckStatus"),
        make_enum_name(FixTags::QuoteCancelType,"QuoteCancelType"),
        make_enum_name(FixTags::QuoteEntryID,"QuoteEntryID"),
        make_enum_name(FixTags::QuoteRejectReason,"QuoteRejectReason"),
        make_enum_name(FixTags::QuoteResponseLevel,"QuoteResponseLevel"),
        make_enum_name(FixTags::QuoteSetID,"QuoteSetID"),
        make_enum_name(FixTags::QuoteRequestType,"QuoteRequestType"),
        make_enum_name(FixTags::TotQuoteEntries,"TotQuoteEntries"),
        make_enum_name(FixTags::UnderlyingIDSource,"UnderlyingIDSource"),
        make_enum_name(FixTags::UnderlyingIssuer,"UnderlyingIssuer"),
        make_enum_name(FixTags::UnderlyingSecurityDesc,"UnderlyingSecurityDesc"),
        make_enum_name(FixTags::UnderlyingSecurityExchange,"UnderlyingSecurityExchange"),
        make_enum_name(FixTags::UnderlyingSecurityID,"UnderlyingSecurityID"),
        make_enum_name(FixTags::UnderlyingSecurityType,"UnderlyingSecurityType"),
        make_enum_name(FixTags::UnderlyingSymbol,"UnderlyingSymbol"),
        make_enum_name(FixTags::UnderlyingSymbolSfx,"UnderlyingSymbolSfx"),
        make_enum_name(FixTags::UnderlyingMaturityMonthYear,"UnderlyingMaturityMonthYear"),
        make_enum_name(FixTags::UnderlyingMaturityDay,"UnderlyingMaturityDay"),
        make_enum_name(FixTags::UnderlyingPutOrCall,"UnderlyingPutOrCall"),
        make_enum_name(FixTags::UnderlyingStrikePrice,"UnderlyingStrikePrice"),
        make_enum_name(FixTags::UnderlyingOptAttribute,"UnderlyingOptAttribute"),
        make_enum_name(FixTags::UnderlyingCurrency,"UnderlyingCurrency"),
        make_enum_name(FixTags::RatioQty,"RatioQty"),
        make_enum_name(FixTags::SecurityReqID,"SecurityReqID"),
        make_enum_name(FixTags::SecurityRequestType,"SecurityRequestType"),
        make_enum_name(FixTags::SecurityResponseID,"SecurityResponseID"),
        make_enum_name(FixTags::SecurityResponseType,"SecurityResponseType"),
        make_enum_name(FixTags::SecurityStatusReqID,"SecurityStatusReqID"),
        make_enum_name(FixTags::UnsolicitedIndicator,"UnsolicitedIndicator"),
        make_enum_name(FixTags::SecurityTradingStatus,"SecurityTradingStatus"),
        make_enum_name(FixTags::HaltReasonChar,"HaltReasonChar"),
        make_enum_name(FixTags::InViewOfCommon,"InViewOfCommon"),
        make_enum_name(FixTags::DueToRelated,"DueToRelated"),
        make_enum_name(FixTags::BuyVolume,"BuyVolume"),
        make_enum_name(FixTags::SellVolume,"SellVolume"),
        make_enum_name(FixTags::HighPx,"HighPx"),
        make_enum_name(FixTags::LowPx,"LowPx"),
        make_enum_name(FixTags::Adjustment,"Adjustment"),
        make_enum_name(FixTags::TradSesReqID,"TradSesReqID"),
        make_enum_name(FixTags::TradingSessionID,"TradingSessionID"),
        make_enum_name(FixTags::ContraTrader,"ContraTrader"),
        make_enum_name(FixTags::TradSesMethod,"TradSesMethod"),
        make_enum_name(FixTags::TradSesMode,"TradSesMode"),
        make_enum_name(FixTags::TradSesStatus,"TradSesStatus"),
        make_enum_name(FixTags::TradSesStartTime,"TradSesStartTime"),
        make_enum_name(FixTags::TradSesOpenTime,"TradSesOpenTime"),
        make_enum_name(FixTags::TradSesPreCloseTime,"TradSesPreCloseTime"),
        make_enum_name(FixTags::TradSesCloseTime,"TradSesCloseTime"),
        make_enum_name(FixTags::TradSesEndTime,"TradSesEndTime"),
        make_enum_name(FixTags::NumberOfOrders,"NumberOfOrders"),
        make_enum_name(FixTags::MessageEncoding,"MessageEncoding"),
        make_enum_name(FixTags::EncodedIssuerLen,"EncodedIssuerLen"),
        make_enum_name(FixTags::EncodedIssuer,"EncodedIssuer"),
        make_enum_name(FixTags::EncodedSecurityDescLen,"EncodedSecurityDescLen"),
        make_enum_name(FixTags::EncodedSecurityDesc,"EncodedSecurityDesc"),
        make_enum_name(FixTags::EncodedListExecInstLen,"EncodedListExecInstLen"),
        make_enum_name(FixTags::EncodedListExecInst,"EncodedListExecInst"),
        make_enum_name(FixTags::EncodedTextLen,"EncodedTextLen"),
        make_enum_name(FixTags::EncodedText,"EncodedText"),
        make_enum_name(FixTags::EncodedSubjectLen,"EncodedSubjectLen"),
        make_enum_name(FixTags::EncodedSubject,"EncodedSubject"),
        make_enum_name(FixTags::EncodedHeadlineLen,"EncodedHeadlineLen"),
        make_enum_name(FixTags::EncodedHeadline,"EncodedHeadline"),
        make_enum_name(FixTags::EncodedAllocTextLen,"EncodedAllocTextLen"),
        make_enum_name(FixTags::EncodedAllocText,"EncodedAllocText"),
        make_enum_name(FixTags::EncodedUnderlyingIssuerLen,"EncodedUnderlyingIssuerLen"),
        make_enum_name(FixTags::EncodedUnderlyingIssuer,"EncodedUnderlyingIssuer"),
        make_enum_name(FixTags::EncodedUnderlyingSecurityDescLen,"EncodedUnderlyingSecurityDescLen"),
        make_enum_name(FixTags::EncodedUnderlyingSecurityDesc,"EncodedUnderlyingSecurityDesc"),
        make_enum_name(FixTags::AllocPrice,"AllocPrice"),
        make_enum_name(FixTags::QuoteSetValidUntilTime,"QuoteSetValidUntilTime"),
        make_enum_name(FixTags::QuoteEntryRejectReason,"QuoteEntryRejectReason"),
        make_enum_name(FixTags::LastMsgSeqNumProcessed,"LastMsgSeqNumProcessed"),
        make_enum_name(FixTags::OnBehalfOfSendingTime,"OnBehalfOfSendingTime"),
        make_enum_name(FixTags::RefTagID,"RefTagID"),
        make_enum_name(FixTags::RefMsgType,"RefMsgType"),
        make_enum_name(FixTags::SessionRejectReason,"SessionRejectReason"),
        make_enum_name(FixTags::BidRequestTransType,"BidRequestTransType"),
        make_enum_name(FixTags::ContraBroker,"ContraBroker"),
        make_enum_name(FixTags::ComplianceID,"ComplianceID"),
        make_enum_name(FixTags::SolicitedFlag,"SolicitedFlag"),
        make_enum_name(FixTags::ExecRestatementReason,"ExecRestatementReason"),
        make_enum_name(FixTags::BusinessRejectRefID,"BusinessRejectRefID"),
        make_enum_name(FixTags::BusinessRejectReason,"BusinessRejectReason"),
        make_enum_name(FixTags::GrossTradeAmt,"GrossTradeAmt"),
        make_enum_name(FixTags::NoContraBrokers,"NoContraBrokers"),
        make_enum_name(FixTags::MaxMessageSize,"MaxMessageSize"),
        make_enum_name(FixTags::NoMsgTypes,"NoMsgTypes"),
        make_enum_name(FixTags::MsgDirection,"MsgDirection"),
        make_enum_name(FixTags::NoTradingSessions,"NoTradingSessions"),
        make_enum_name(FixTags::TotalVolumeTraded,"TotalVolumeTraded"),
        make_enum_name(FixTags::DiscretionInst,"DiscretionInst"),
        make_enum_name(FixTags::DiscretionOffset,"DiscretionOffset"),
        make_enum_name(FixTags::BidID,"BidID"),
        make_enum_name(FixTags::ClientBidID,"ClientBidID"),
        make_enum_name(FixTags::ListName,"ListName"),
        make_enum_name(FixTags::TotalNumSecurities,"TotalNumSecurities"),
        make_enum_name(FixTags::BidType,"BidType"),
        make_enum_name(FixTags::NumTickets,"NumTickets"),
        make_enum_name(FixTags::SideValue1,"SideValue1"),
        make_enum_name(FixTags::SideValue2,"SideValue2"),
        make_enum_name(FixTags::NoBidDescriptors,"NoBidDescriptors"),
        make_enum_name(FixTags::BidDescriptorType,"BidDescriptorType"),
        make_enum_name(FixTags::BidDescriptor,"BidDescriptor"),
        make_enum_name(FixTags::SideValueInd,"SideValueInd"),
        make_enum_name(FixTags::LiquidityPctLow,"LiquidityPctLow"),
        make_enum_name(FixTags::LiquidityPctHigh,"LiquidityPctHigh"),
        make_enum_name(FixTags::LiquidityValue,"LiquidityValue"),
        make_enum_name(FixTags::EFPTrackingError,"EFPTrackingError"),
        make_enum_name(FixTags::FairValue,"FairValue"),
        make_enum_name(FixTags::OutsideIndexPct,"OutsideIndexPct"),
        make_enum_name(FixTags::ValueOfFutures,"ValueOfFutures"),
        make_enum_name(FixTags::LiquidityIndType,"LiquidityIndType"),
        make_enum_name(FixTags::WtAverageLiquidity,"WtAverageLiquidity"),
        make_enum_name(FixTags::ExchangeForPhysical,"ExchangeForPhysical"),
        make_enum_name(FixTags::OutMainCntryUIndex,"OutMainCntryUIndex"),
        make_enum_name(FixTags::CrossPercent,"CrossPercent"),
        make_enum_name(FixTags::ProgRptReqs,"ProgRptReqs"),
        make_enum_name(FixTags::ProgPeriodInterval,"ProgPeriodInterval"),
        make_enum_name(FixTags::IncTaxInd,"IncTaxInd"),
        make_enum_name(FixTags::NumBidders,"NumBidders"),
        make_enum_name(FixTags::TradeType,"TradeType"),
        make_enum_name(FixTags::BasisPxType,"BasisPxType"),
        make_enum_name(FixTags::NoBidComponents,"NoBidComponents"),
        make_enum_name(FixTags::Country,"Country"),
        make_enum_name(FixTags::TotNoStrikes,"TotNoStrikes"),
        make_enum_name(FixTags::PriceType,"PriceType"),
        make_enum_name(FixTags::DayOrderQty,"DayOrderQty"),
        make_enum_name(FixTags::DayCumQty,"DayCumQty"),
        make_enum_name(FixTags::DayAvgPx,"DayAvgPx"),
        make_enum_name(FixTags::GTBookingInst,"GTBookingInst"),
        make_enum_name(FixTags::NoStrikes,"NoStrikes"),
        make_enum_name(FixTags::ListStatusType,"ListStatusType"),
        make_enum_name(FixTags::NetGrossInd,"NetGrossInd"),
        make_enum_name(FixTags::ListOrderStatus,"ListOrderStatus"),
        make_enum_name(FixTags::ExpireDate,"ExpireDate"),
        make_enum_name(FixTags::ListExecInstType,"ListExecInstType"),
        make_enum_name(FixTags::CxlRejResponseTo,"CxlRejResponseTo"),
        make_enum_name(FixTags::UnderlyingCouponRate,"UnderlyingCouponRate"),
        make_enum_name(FixTags::UnderlyingContractMultiplier,"UnderlyingContractMultiplier"),
        make_enum_name(FixTags::ContraTradeQty,"ContraTradeQty"),
        make_enum_name(FixTags::ContraTradeTime,"ContraTradeTime"),
        make_enum_name(FixTags::ClearingFirm,"ClearingFirm"),
        make_enum_name(FixTags::ClearingAccount,"ClearingAccount"),
        make_enum_name(FixTags::LiquidityNumSecurities,"LiquidityNumSecurities"),
        make_enum_name(FixTags::MultiLegReportingType,"MultiLegReportingType"),
        make_enum_name(FixTags::StrikeTime,"StrikeTime"),
        make_enum_name(FixTags::ListStatusText,"ListStatusText"),
        make_enum_name(FixTags::EncodedListStatusTextLen,"EncodedListStatusTextLen"),
        make_enum_name(FixTags::EncodedListStatusText,"EncodedListStatusText"));

